chore: refactor RetryContext#recordError to return the throwable provided to it instead of blindly wrapping everything in a CancelledException
Add Hasher#hash(ByteString) and Hasher#validateUnchecked(ByteString) that will throw an unchecked exception instead of a checked IOException.

When a retry budget is exhaused a supressed execption with a comment will be included with comment details.

A multi attempt failure will now look like:
```
com.google.api.gax.rpc.ResourceExhaustedException: {resource exhausted}
  at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:60)
  at com.google.cloud.storage.RetryContextTest.apiException(RetryContextTest.java:186)
  at com.google.cloud.storage.RetryContextTest.retryable_cancelledException_when_maxAttemptBudget_multipleAttempts_previousErrorsIncludedAsSuppressed(RetryContextTest.java:70)
  ... test runner frames
  Suppressed: com.google.cloud.storage.RetryContext$RetryBudgetExhaustedComment: Operation failed to complete within retry limit (attempts: 3, maxAttempts: 3) previous failures follow in order of occurrence
  Suppressed: com.google.api.gax.rpc.UnavailableException: {unavailable}
    at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:72)
    at com.google.cloud.storage.RetryContextTest.apiException(RetryContextTest.java:186)
    at com.google.cloud.storage.RetryContextTest.retryable_cancelledException_when_maxAttemptBudget_multipleAttempts_previousErrorsIncludedAsSuppressed(RetryContextTest.java:68)
    ... 27 more
  Suppressed: com.google.api.gax.rpc.InternalException: {internal}
    at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:70)
    at com.google.cloud.storage.RetryContextTest.apiException(RetryContextTest.java:186)
    at com.google.cloud.storage.RetryContextTest.retryable_cancelledException_when_maxAttemptBudget_multipleAttempts_previousErrorsIncludedAsSuppressed(RetryContextTest.java:69)
    ... 27 more
```

A single attempt failure will now look like:
```
com.google.api.gax.rpc.UnavailableException: {unavailable}
  at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:72)
  at com.google.cloud.storage.RetryContextTest.apiException(RetryContextTest.java:186)
  at com.google.cloud.storage.RetryContextTest.nonretryable_cancelledException_regardlessOfAttemptBudget(RetryContextTest.java:94)
  ... test runner frames
  Suppressed: com.google.cloud.storage.RetryContext$RetryBudgetExhaustedComment: Unretryable error (attempts: 1, maxAttempts: 3)
```